import { AnimeSelections } from './AnimeSelections';
import { ReflectionCard } from './PersonalCards';
import { CategoryGoals, CollaborationLinks } from './CategoryGoals';
import { GamingSection } from './GamingSection';
import { SocialIcon } from './SocialIcon';
import { animeLinks } from './content';
import { expandedLibraryShelves as libraryShelves } from './library-content';
import type { ReactNode } from 'react';
function Out({href,children,className=''}:{href:string;children:ReactNode;className?:string}) {return <a href={href} className={className} target={href.startsWith('mailto:')?undefined:'_blank'} rel={href.startsWith('mailto:')?undefined:'noreferrer'}>{children}</a>;}
function Label({children}:{children:ReactNode}) {return <p className="eyebrow section-label"><span/>{children}</p>;}

export default function ArtsPage() { return <section id="culture" className="culture-section room-section" tabIndex={-1}><div className="room-backdrop culture-backdrop" aria-hidden="true"><img src="/assets/culture-room.webp" alt="" width="960" height="720" loading="eager"/></div><div className="section-shell"><div className="culture-title reveal"><Label>ARTS & CULTURE</Label><h1 id="page-title">Other worlds.<br/><em>Wider horizons.</em></h1></div><div className="culture-grid"><div className="library-invite reveal"><span className="eyebrow">THE LIBRARY</span><h3>A few hundred<br/>ways to <em>escape.</em></h3><p>Film, anime, manga, art and the imagination behind them. A growing collection of stories on screen and on the page.</p><a href="/library/" className="pill-link">Browse the Library </a><div className="shelf-counts"><a href="/library/#screen"><strong>{libraryShelves[0].titles.length}</strong><span>On screen </span></a><a href="/library/#reading"><strong>{libraryShelves[1].titles.length}</strong><span>On the page </span></a></div></div><div className="culture-reflection reveal"><ReflectionCard image="/media/personal/art-portrait.webp" alt="Sora among framed artworks in a warmly lit interior." title="Why stories stay with me" text="The craft. The cinematography. The impossible made visible. I appreciate the imagination and work behind creating a world you can feel."/><span className="image-caption">Among the frames</span></div></div><aside id="anime-finds" className="anime-finds reveal" tabIndex={-1}><div><span className="eyebrow">ANIME FINDS</span><h3>Another world, one tap away.</h3><p>Small discoveries beyond the library.</p></div>{animeLinks.map(link=><Out key={link.url} href={link.url} className="anime-link"><SocialIcon platform="TikTok"/><span>{link.label}<small>{link.detail}</small></span></Out>)}</aside><AnimeSelections/><GamingSection/><CategoryGoals category="culture"/><div className="culture-collaboration reveal"><h3>Let’s make room for imagination.</h3><p>Art, animation, games or a creative community. I’m always interested in where a shared idea can go.</p><CollaborationLinks category="culture"/></div></div></section>; }
