import { useState } from 'react';
import { bucketItems, bucketCategories, filterBucket } from './bucket-content';
import type { BucketItem, BucketCategory } from './bucket-content';
import { validDate, dateLabel } from './collection-utils';
import './catalogue.css';
function CategoryIcon({type}:{type:BucketCategory}){return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round" strokeLinecap="round"><path d={type==='travel'?'m3 10 8 2 8-9 2 2-8 9 2 7-3-3-3-2-4 3-2-2 4-4Z':type==='learning'?'M12 5C8 2 3 3 3 3v16s5-1 9 2c4-3 9-2 9-2V3s-5-1-9 2Zm0 0v16':type==='career'?'M3 8h18v12H3ZM8 8V4h8v4M3 12l9 3 9-3M12 13v4':type==='home'?'m2 11 10-9 10 9M5 9v12h14V9M10 21v-8h4v8':type==='music'?'M9 18V5l11-2v12M9 8l11-2M9 18a3 3 0 1 1-3-3c2 0 3 1 3 3Zm11-3a3 3 0 1 1-3-3c2 0 3 1 3 3Z':type==='recognition'?'M7 3h10v7a5 5 0 0 1-10 0ZM7 5H3v3c0 3 4 4 4 4m10-7h4v3c0 3-4 4-4 4M12 15v6M8 21h8':'M12 21S2 15 2 8c0-6 8-6 10-1 2-5 10-5 10 1 0 7-10 13-10 13Z'}/></svg>;}
export function BucketList(){
 const [tab,setTab]=useState<'life'|'adult'>('life'),[adult,setAdult]=useState<BucketItem[]|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(false);
 const [category,setCategory]=useState('all'),[status,setStatus]=useState('all');
 const select=(next:'life'|'adult')=>{setTab(next);setCategory('all');setStatus('all');};
 async function confirm(){setLoading(true);setError(false);try{const data=await import('./bucket-adult');setAdult(data.adultBucketItems);}catch{setError(true);}finally{setLoading(false);}}
 const list=filterBucket(tab==='life'?bucketItems:adult||[],category,status);
 return <section id="bucket-list" className="bucket-section" aria-labelledby="bucket-title" tabIndex={-1}><div className="bucket-heading"><div><p className="eyebrow">A LIFE TO EXPLORE</p><h3 id="bucket-title">The Bucket List.</h3></div><p>Things I want to try, learn, make and experience.<br/>My list, at my own pace.</p></div><div className="bucket-tabs" role="tablist" aria-label="Bucket List collections">{(['life','adult'] as const).map((id,i)=><button key={id} id={`bucket-tab-${id}`} role="tab" aria-selected={tab===id} aria-controls={`bucket-panel-${id}`} tabIndex={tab===id?0:-1} onClick={()=>select(id)} onKeyDown={event=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(event.key)){event.preventDefault();const next=event.key==='Home'?'life':event.key==='End'?'adult':i===0?'adult':'life';select(next);document.getElementById(`bucket-tab-${next}`)?.focus();}}}>{id==='life'?'Life list':'18+'}</button>)}</div>
 <div id={`bucket-panel-${tab}`} role="tabpanel" aria-labelledby={`bucket-tab-${tab}`} tabIndex={0}>
 {tab==='adult'&&!adult?<div className="adult-gate"><span className="adult-badge">18+</span><h4>A more personal part of the list.</h4><p>This collection contains intimate adult aspirations. Please confirm you are 18 or older to view it.</p><button type="button" className="pill-link" onClick={confirm} disabled={loading}>{loading?'Opening collection':'I am 18 or older'}</button><button className="gate-back" onClick={()=>select('life')}>Back to life list</button>{error&&<p role="alert">The collection could not load. Please try again.</p>}</div>:<>
 <div className="bucket-filters"><label>Category<select value={category} onChange={event=>setCategory(event.target.value)}><option value="all">All categories</option>{Object.entries(bucketCategories).filter(([id])=>tab==='life'||id==='personal').map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Progress<select value={status} onChange={event=>setStatus(event.target.value)}><option value="all">All progress</option><option value="unmarked">Unmarked</option><option value="in-progress">In progress</option><option value="complete">Complete</option></select></label><p role="status">{list.length} aspirations</p></div>
 {list.length?<ul className="bucket-list">{list.map(item=><li key={item.id}><span className="bucket-icon"><CategoryIcon type={item.category}/></span><div><h4>{item.title}</h4><span className={`bucket-status status-${item.status}`}>{item.status==='complete'?'Complete':item.status==='in-progress'?'In progress':'Unmarked'}</span>{item.status==='complete'&&validDate(item.completedOn)&&<time dateTime={item.completedOn}> · {dateLabel(item.completedOn)}</time>}{item.note&&<p className="bucket-note">Note: {item.note}</p>}</div></li>)}</ul>:<p className="bucket-empty">No aspirations with this filter yet.</p>}<p className="bucket-footnote">Progress is my own record. Completion updates will follow.</p></>}
 </div></section>;
}
