import { useState } from 'react';
import { catalogueEntries, writingCards } from './catalogue-content';
import type { CatalogueEntry } from './catalogue-content';
import { groupCatalogue, dateLabel, validDate } from './collection-utils';
import { SocialIcon } from './SocialIcon';
import './catalogue.css';
function Cover({entry}:{entry:CatalogueEntry}){
  return entry.video?<video controls playsInline preload="none" poster={entry.image} src={entry.video} aria-label={entry.title}/>:entry.image?<img src={entry.image} alt={entry.imageAlt||''} loading="lazy" width="800" height="500"/>:<div className={`catalogue-cover cover-${entry.cover}`} aria-hidden="true"><img src="/assets/culture-room.webp" alt="" width="960" height="720" loading="lazy"/><span>{entry.cover==='isekai'?'15':'NEXT'}</span><small>{entry.cover==='isekai'?'OTHER WORLDS':'ON MY RADAR'}</small><i/></div>;
}
export function CatalogueCard({entry}:{entry:CatalogueEntry}){return <article className="catalogue-card"><div className="catalogue-card-media"><Cover entry={entry}/></div><div className="catalogue-card-copy"><span className="eyebrow">{entry.category}</span><h3><a href={entry.url} target="_blank" rel="noreferrer">{entry.title}</a></h3><p>{entry.description}</p><a className="catalogue-source" href={entry.url} target="_blank" rel="noreferrer"><SocialIcon platform={entry.source}/><span>View on {entry.source}</span></a></div></article>;}
export function CataloguePreview(){return <section id="catalogue-preview" className="catalogue-preview section-shell"><div className="catalogue-heading"><div><p className="eyebrow">COLLECTED ALONG THE WAY</p><h2>A little of what<br/>caught my <em>eye.</em></h2></div><a className="pill-link" href="/catalogue/">Open the Catalogue</a></div><div className="catalogue-grid">{catalogueEntries.slice(0,2).map(entry=><CatalogueCard key={entry.id} entry={entry}/>)}</div></section>;}
export function WritingCards(){return <section id="writing" className="writing-section" aria-labelledby="writing-title" tabIndex={-1}><div><p className="eyebrow">NOTES & LONGER THOUGHTS</p><h3 id="writing-title">A thought worth<br/>staying with.</h3></div><div>{writingCards.map(card=><article className="writing-card" key={card.id}><img src={card.image} alt={card.imageAlt} width="800" height="600" loading="lazy"/><div><span className="eyebrow">{card.kind==='profile'?'SUBSTACK PROFILE':'ON SUBSTACK'}</span><h4>{card.title}</h4><p>{card.description}</p>{validDate(card.date)&&<time dateTime={card.date}>{dateLabel(card.date)}</time>}<a href={card.url} target="_blank" rel="noreferrer">{card.kind==='profile'?'Visit my Substack profile':'Read on Substack'}</a></div></article>)}</div></section>;}
export default function Catalogue(){
  const [category,setCategory]=useState('All');
  const categories=['All',...new Set(catalogueEntries.map(entry=>entry.category))];
  const entries=catalogueEntries.filter(entry=>category==='All'||entry.category===category);
  return <div className="catalogue-page section-shell"><header className="catalogue-intro"><p className="eyebrow">A PERSONAL RECORD</p><h1>The <em>Catalogue.</em></h1><p>Things I share. Things I find. A few things worth keeping.</p><span>Posts, releases and moments, collected as they happen.</span></header><nav id="collection" tabIndex={-1} className="collection-filters" aria-label="Catalogue categories">{categories.map(item=><button key={item} type="button" aria-pressed={category===item} onClick={()=>setCategory(item)}>{item}</button>)}</nav><div aria-live="polite" className="sr-only">{entries.length} entries</div>{groupCatalogue(entries).map(group=><section className="collection-group" key={group.key}><h2>{group.label}</h2><div className="catalogue-grid">{group.entries.map(entry=><CatalogueCard key={entry.id} entry={entry}/>)}</div></section>)}<WritingCards/><div className="catalogue-end"><p>A growing collection, at my own pace.</p><a className="text-link" href="/arts/">Explore Arts & Culture</a></div></div>;
}
