import { HeroAtmosphere } from './HeroAtmosphere';
import { Arrow, Star } from './Icons';
import { WorldArt, Vinyl, Equalizer } from './WorldArt';
import { ReflectionCard, MusicPhotographs } from './PersonalCards';
import { TechSection } from './TechSection';
import { libraryShelves, musicLinks, playlistLinks } from './content';
import type { ReactNode } from 'react';

function Out({href,children,className=''}:{href:string;children:ReactNode;className?:string}) {return <a href={href} className={className} target={href.startsWith('mailto:')?undefined:'_blank'} rel={href.startsWith('mailto:')?undefined:'noreferrer'}>{children}</a>;}
function Label({children}:{children:ReactNode}) {return <p className="eyebrow section-label"><span/>{children}</p>;}
export function Home({paused,setPaused,reducedMotion}:{paused:boolean;setPaused:(value:boolean)=>void;reducedMotion:boolean}) {
  return <>
    <section className="hero" aria-labelledby="hero-title">
      <HeroAtmosphere paused={paused}/><div className="hero-print" aria-hidden="true"/><div className="hero-sun" aria-hidden="true"/>
      <span className="hero-side-note" aria-hidden="true">A LIFE WITH MANY SIDES</span>
      <div className="hero-title-wrap"><div className="hero-kicker"><span className="hero-the">The</span><span className="eyebrow">SOUND, STORIES & EVERYTHING IN BETWEEN</span></div><h1 id="hero-title" aria-label="The Soraverse">Soraverse</h1><p className="hero-welcome">Welcome to my <em>wonderland.</em></p></div>
      <WorldArt kind="culture" className="hero-book"/><Vinyl className="hero-record"/><Star className="hero-spark"/>
      <div className="hero-bottom"><p>A place for the things I build,<br/>the sounds I love and the worlds I explore.</p><a className="explore-down" href="#about"><span>Come on in</span><span className="circle-arrow"><Arrow/></span></a><button className="motion-toggle" onClick={()=>setPaused(!paused)} disabled={reducedMotion} aria-pressed={paused||reducedMotion} aria-label={reducedMotion?'Reduced motion enabled':paused?'Resume atmospheric motion':'Pause atmospheric motion'}><span aria-hidden="true">{paused||reducedMotion?'Ⅱ':'≋'}</span>{reducedMotion?'Reduced motion':paused?'Motion paused':'Motion on'}</button></div>
    </section>
    <nav className="chapter-strip" aria-label="Explore my interests">{[{id:'music',name:'For the feeling',label:'Music & DJ',kind:'music'},{id:'tech',name:'For the possibilities',label:'Tech & Business',kind:'tech'},{id:'culture',name:'For the imagination',label:'Arts & Culture',kind:'culture'},{id:'ideas',name:'For the questions',label:'Society & Ideas',kind:'ideas'}].map(x=><a href={`#${x.id}`} key={x.id} className={`chapter-${x.id}`}><span><small>{x.name}</small>{x.label}</span><Arrow diagonal/></a>)}</nav>

    <section id="about" className="about-section section-shell" tabIndex={-1}>
      <div className="about-portrait reveal"><ReflectionCard image="/media/personal/sora-intro.webp" alt="Sora in sunglasses, a white linen shirt and patterned red trousers against a cinematic blue backdrop." title="Why I make time for this" text="Our time is finite. I want to spend mine paying attention, making things and discovering more."/><span className="portrait-note">Hello, I'm Sora <Star/></span></div>
      <div className="about-copy reveal"><Label>THE PERSON BETWEEN THE INTERESTS</Label><h2>I build things.<br/>I play music.<br/>I <em>stay curious.</em></h2><p>Technical project manager, DJ and event organiser. I'm interested in how technology changes the way we live, how people create, and how a good story opens up another world.</p><p>This is my little corner of the internet. A collection of work, sounds, stories and things worth paying attention to.</p><details className="profile-details"><summary>A little more about me <span aria-hidden="true">+</span></summary><div><p>I studied Industrial Physics, Electronics & IT at Covenant University. My work has taken me from IT operations and corporate banking into technology advisory and building products.</p><p>I appreciate human creativity in its many forms. Beautiful cinematography, a room finding its rhythm, a new idea that changes how we see things. I want to make room for all of it.</p><Out href="https://tobiarogunmati.com/" className="text-link">My professional background <Arrow diagonal/></Out></div></details><div className="about-signoff"><Star/><span>Many interests. One life to explore them.</span></div></div>
    </section>

    <section id="music" className="music-section" tabIndex={-1}><div className="section-shell">
      <div className="section-heading reveal"><div><Label>MUSIC & DJ</Label><h2>Life has a<br/><em>soundtrack.</em></h2></div><p>Some days I find it.<br/>Some nights I play it.<br/><span>Sounds to get lost in. People to find them with.</span></p></div>
      <div className="music-main"><div className="music-art reveal"><div className="illustration-frame"><img src="/media/personal/dj-illustration.webp" alt="Illustrated portrait of Sora wearing headphones behind the decks, surrounded by colourful expressive brushwork." width="1086" height="1448" loading="lazy"/><span className="image-stamp">IN MY ELEMENT</span></div><Vinyl className="music-record"/><div className="dj-intro"><h3>Sora, behind the decks.</h3><p>DJ and event organiser in Lagos. Sets rooted in house, and spaces where people come together.</p><div className="genre-chips">{['House','EDM','Afro House','Afro Tech','GQOM'].map(x=><span key={x}>{x}</span>)}</div></div></div>
      <div className="music-directory reveal"><div className="listen-top"><span className="eyebrow">THE LISTENING LINKS</span><Equalizer/></div><Out href="https://soundcloud.com/soralive" className="platform-link"><span>SoundCloud<small>My profile and recorded sets</small></span><Arrow diagonal/></Out><Out href="https://linktr.ee/rogueskye" className="platform-link"><span>Playlists & more<small>Find my selections on Linktree</small></span><Arrow diagonal/></Out><div id="sets" className="list-heading" tabIndex={-1}><span>RECORDED SETS</span><span>06</span></div><div className="set-list">{musicLinks.filter(x=>x.url.includes('soundcloud.com/soralive/')).map((link,i)=><Out href={link.url} className="set-link" key={link.url}><span className="set-number">{String(i+1).padStart(2,'0')}</span><span>{link.label}</span><Arrow diagonal/></Out>)}</div><details id="playlists" className="playlist-details" tabIndex={-1}><summary>Playlists & selections <span aria-hidden="true">+</span></summary><div>{playlistLinks.map(link=><Out key={link.label} href={link.url} className="set-link"><span>{link.label}<small>{link.detail}</small></span><Arrow diagonal/></Out>)}</div></details><p className="link-footnote">All music opens on its original platform.</p></div></div>
      <div id="events" className="music-events reveal" tabIndex={-1}><MusicPhotographs/><div className="event-copy"><Label>LET'S MAKE A NIGHT OF IT</Label><h3>Good people.<br/>Good music.<br/><em>Something to remember.</em></h3><p>DJ sets, event organising and shared ideas that deserve a dance floor.</p><Out href="mailto:Him@soralives.xyz" className="pill-link">Talk music & events <Arrow diagonal/></Out><div className="mini-room"><img src="/assets/music-room.webp" alt="" width="960" height="720" loading="lazy"/><span className="eyebrow">THE LISTENING ROOM</span></div></div></div>
    </div></section>

    <TechSection paused={paused||reducedMotion}/>

    <section id="culture" className="culture-section" tabIndex={-1}><div className="section-shell"><div className="culture-title reveal"><Label>ARTS & CULTURE</Label><h2>Other worlds.<br/><em>Wider horizons.</em></h2><WorldArt kind="culture"/></div><div className="culture-grid"><div className="library-invite reveal"><span className="eyebrow">THE LIBRARY</span><h3>A few hundred<br/>ways to <em>escape.</em></h3><p>Film, anime, manga, art and the imagination behind them. A growing collection of stories on screen and on the page.</p><a href="/library/" className="pill-link">Browse the Library <Arrow/></a><div className="shelf-counts"><a href="/library/#screen"><strong>{libraryShelves[0].titles.length}</strong><span>On screen <Arrow diagonal/></span></a><a href="/library/#reading"><strong>{libraryShelves[1].titles.length}</strong><span>On the page <Arrow diagonal/></span></a></div><img className="culture-room" src="/assets/culture-room.webp" alt="" width="960" height="720" loading="lazy"/></div><div className="culture-reflection reveal"><ReflectionCard image="/media/personal/art-portrait.webp" alt="Sora among framed artworks in a warmly lit interior." title="Why stories stay with me" text="The craft. The cinematography. The impossible made visible. I appreciate the imagination and work behind creating a world you can feel."/><span className="image-caption">Among the frames</span></div></div></div></section>

    <section id="ideas" className="ideas-section" tabIndex={-1}><div className="section-shell ideas-layout"><div className="ideas-copy reveal"><Label>SOCIETY & IDEAS</Label><h2>The world is<br/>worth <em>wondering<br/>about.</em></h2><p>History, politics, psychology, culture and belief. I'm interested in how people have shaped one another across time, and what those stories reveal about the world we live in.</p><div className="interest-words"><span>History & power</span><span>Culture & belief</span><span>Human behaviour</span><span>Espionage & intrigue</span></div><Out href="https://substack.com/@soralive" className="pill-link">Notes & thoughts on Substack <Arrow diagonal/></Out></div><div className="ideas-art reveal"><WorldArt kind="ideas"/><span className="orbit-note">KEEP ASKING<br/>BETTER QUESTIONS.</span><img src="/assets/ideas-room.webp" alt="" width="960" height="720" loading="lazy"/></div></div></section>

    <section className="closing-note section-shell reveal"><Star/><p>Music gives shape to our time.<br/>Art gives character to our space.<br/><em>Curiosity makes room for more.</em></p><a href="#contact" className="circle-arrow" aria-label="Get in touch"><Arrow/></a></section>
  </>;
}
