export const experienceItems = [
  {
    id: 'shell', company: 'Shell', division: 'SNEPCo', sector: 'Upstream oil & gas',
    period: 'JANUARY TO JUNE 2015', year: '2015', role: 'IT Services & Operations',
    position: 'Undergraduate internship',
    summary: 'Keeping people connected to the systems they need, from the office to offshore teams.',
    detail: 'Desktop and remote support, installations and IT inventory.',
    skills: ['IT operations', 'Remote support', 'Windows', 'Linux', 'macOS'],
    accent: 'gold', logo: '/media/companies/shell.webp',
  },
  {
    id: 'ecm', company: 'ECM Terminals', division: 'Ecomarine', sector: 'Terminal operations',
    period: 'MARCH TO DECEMBER 2017', year: '2017', role: 'IT Operations Specialist',
    position: 'Operational technology',
    summary: 'Supporting the everyday systems behind a working terminal.',
    detail: 'Software, hardware and networks, with Excel templates for budgets and forecasts.',
    skills: ['IT support', 'Networks', 'Excel', 'Database operations'],
    accent: 'teal', logo: '/media/companies/ecm.webp',
  },
  {
    id: 'gtbank', company: 'GTBank', division: 'Corporate Banking', sector: 'Pan African banking',
    period: 'AUGUST 2018 TO MARCH 2021', year: '2018 to 2021', role: 'Relationship Manager',
    position: 'Corporate banking',
    summary: 'Connecting business ambition with the right financial solutions.',
    detail: 'Client relationships across credit, trade finance, payments and digital collections.',
    skills: ['Credit structuring', 'Trade finance', 'Client strategy', 'Digital collections'],
    accent: 'coral', logo: '/media/companies/gtbank.webp',
  },
  {
    id: 'kpmg', company: 'KPMG', division: 'Nigeria', sector: 'Technology advisory',
    period: 'OCTOBER 2021 TO PRESENT', year: '2021 to now', role: 'Technology Advisory',
    position: 'Experienced Analyst to Assistant Manager',
    summary: 'Bringing business needs, people and complex technology into alignment.',
    detail: 'Banking transformation across requirements, integrations, testing and delivery.',
    skills: ['Programme delivery', 'Integration', 'QA & UAT', 'Vendor management'],
    accent: 'blue', logo: '/media/companies/kpmg.webp',
  },
] as const;

export const toolkitGroups = [
  { title: 'Delivery & analysis', icon: 'delivery', items: ['Requirements', 'QA & UAT', 'Vendor management'] },
  { title: 'Product engineering', icon: 'code', items: ['React', 'TypeScript', 'Next.js'] },
  { title: 'Enterprise platforms', icon: 'systems', items: ['Calypso', 'Oracle FLEXCUBE', 'Temenos'] },
  { title: 'Design & collaboration', icon: 'design', items: ['Figma', 'Jira', 'Azure Test Plans'] },
  { title: 'Data & infrastructure', icon: 'data', items: ['PostgreSQL', 'Payload CMS', 'Vercel'] },
  { title: 'AI assisted building', icon: 'ai', items: ['Claude Code', 'Codex'] },
] as const;

export const professionalProjects = [
  {
    id: 'delphi', name: 'Delphi', status: 'Public website',
    headline: 'Make the connections.',
    summary: 'A connected atlas of Nigerian technology. Companies, investors, funding and people, brought together so the bigger picture becomes easier to see.',
    highlights: ['Connected entity profiles', 'Search & discovery', 'Editorial workflows'],
    stack: ['Next.js', 'TypeScript', 'Payload CMS', 'PostgreSQL', 'Vercel'],
    tags: ['Ecosystem intelligence', 'Connected information'],
    url: 'https://delphiatlas.com/', linkLabel: 'Explore Delphi',
    screenshot: '/media/projects/delphi.webp', screenshotLabel: 'Website preview',
    screenshotAlt: 'Delphi website introducing its structured atlas of the Nigerian technology ecosystem.',
    film: '/media/projects/delphi.mp4', poster: '/media/projects/delphi.poster.webp',
    filmLabel: 'Product film', duration: '0:23',
    filmDescription: 'An introduction to the Delphi ecosystem atlas using illustrative interface recreations. These scenes explain the product concept rather than record a live browsing session.',
  },
  {
    id: 'hades', name: 'Hades', status: 'Live',
    headline: 'Find your useful internet.',
    summary: 'Tools, apps, websites and resources worth knowing about. An organised directory for work, creativity, learning, everyday life and the occasional rabbit hole.',
    highlights: ['Ten broad subject areas', 'Searchable resources', 'A little serendipity'],
    stack: ['JavaScript', 'Node.js', 'CSS', 'Google Sheets', 'Vercel Functions'],
    tags: ['Useful tools', 'Discovery'],
    url: 'https://hades.soralives.xyz/', linkLabel: 'Explore Hades',
    screenshot: '/media/projects/hades.webp', screenshotLabel: 'Live directory',
    screenshotAlt: 'Hades directory with subject navigation and a selection of resources to explore.',
    film: '/media/projects/hades.mp4', poster: '/media/projects/hades.poster.webp',
    filmLabel: 'Launch film', duration: '0:40',
    filmDescription: 'A visual introduction to Hades, showing its directory, subject areas and resource discovery. The film uses music and on screen text.',
  },
  {
    id: 'odyssey', name: 'Odyssey', status: 'In development',
    headline: 'Give curiosity somewhere to go.',
    summary: 'A project about living with intention. Explore interests, discover communities and turn things you want to try into sidequests worth stepping outside for.',
    highlights: ['Guided exploration', 'Communities & activities', 'Sidequests & progression'],
    stack: ['Next.js', 'React', 'TypeScript', 'CSS'],
    tags: ['Intentional living', 'Sidequests'],
    url: null, linkLabel: null,
    screenshot: '/media/projects/odyssey.webp', screenshotLabel: 'Landing preview',
    screenshotAlt: 'Odyssey landing page preview introducing the idea of turning interests into real experiences.',
    film: '/media/projects/odyssey.mp4', poster: '/media/projects/odyssey.poster.webp',
    filmLabel: 'Concept film', duration: '0:40',
    filmDescription: 'Break the Loop introduces Odyssey through the idea of taking a new turn. Sidequests, communities, rankings and leaderboards describe the planned product. The current implementation is a landing preview.',
  },
] as const;

export type ProfessionalProject = typeof professionalProjects[number];
