import { AnimatedPortrait } from './AnimatedPortrait';
import type { PageProps } from './page-types';
import { Vinyl, Equalizer } from './WorldArt';
import { MusicPhotographs } from './PersonalCards';
import { CategoryGoals, CollaborationLinks } from './CategoryGoals';
import { musicLinks, playlistLinks } from './content';
import type { ReactNode } from 'react';
function Out({href,children,className=''}:{href:string;children:ReactNode;className?:string}) {return <a href={href} className={className} target={href.startsWith('mailto:')?undefined:'_blank'} rel={href.startsWith('mailto:')?undefined:'noreferrer'}>{children}</a>;}
function Label({children}:{children:ReactNode}) {return <p className="eyebrow section-label"><span/>{children}</p>;}

export default function SoundPage({paused}:PageProps) { return <section id="music" className="music-section room-section" tabIndex={-1}><div className="room-backdrop music-backdrop" aria-hidden="true"><img src="/assets/music-room.webp" alt="" width="960" height="720" loading="eager"/></div><div className="section-shell">
      <div className="section-heading reveal"><div><Label>MUSIC & DJ</Label><h1 id="page-title">Life has a<br/><em>soundtrack.</em></h1></div><p>Some days I find it.<br/>Some nights I play it.<br/><span>Sounds to get lost in. People to find them with.</span></p></div>
      <div className="music-main"><div className="music-art reveal"><div className="illustration-frame"><AnimatedPortrait paused={paused}/></div><Vinyl className="music-record"/><div className="dj-intro"><h3>Sora, DJ and Community Partner</h3><p>Sets rooted in house. Events, collaborations and spaces where people come together.</p><div className="genre-chips">{['House','EDM','Afro House','Afro Tech','GQOM'].map(x=><span key={x}>{x}</span>)}</div></div></div>
      <div className="music-directory reveal"><div className="listen-top"><span className="eyebrow">THE LISTENING LINKS</span><Equalizer/></div><Out href="https://soundcloud.com/soralive" className="platform-link"><span>SoundCloud<small>My profile and recorded sets</small></span></Out><Out href="https://linktr.ee/rogueskye" className="platform-link"><span>Playlists & more<small>Find my selections on Linktree</small></span></Out><div id="sets" className="list-heading" tabIndex={-1}><span>RECORDED SETS</span><span>06</span></div><div className="set-list">{musicLinks.filter(x=>x.url.includes('soundcloud.com/soralive/')).map((link,i)=><Out href={link.url} className="set-link" key={link.url}><span className="set-number">{String(i+1).padStart(2,'0')}</span><span>{link.label}</span></Out>)}</div><details id="playlists" className="playlist-details" tabIndex={-1}><summary>Playlists & selections <span aria-hidden="true">+</span></summary><div>{playlistLinks.map(link=><Out key={link.label} href={link.url} className="set-link"><span>{link.label}<small>{link.detail}</small></span></Out>)}</div></details><p className="link-footnote">All music opens on its original platform.</p></div></div>
      <CategoryGoals category="music"/>
      <div id="events" className="music-events reveal" tabIndex={-1}><MusicPhotographs/><div className="event-copy"><Label>LET'S MAKE A NIGHT OF IT</Label><h3>Good people.<br/>Good music.<br/><em>Something to remember.</em></h3><p>DJ sets, event organising and shared ideas that deserve a dance floor.</p><CollaborationLinks category="music"/><p className="eyebrow room-caption">THE LISTENING ROOM</p></div></div>
    </div></section>; }
